export const aptitudeQuestionSets = [
  // SET 1
  [
    {
      id: 1,
      question: "What is 15 + 27?",
      options: ["42", "40", "45", "48"],
      correctAnswerIndex: 0,
      category: "logical",
    },
    {
      id: 2,
      question: "Which number comes next: 2, 4, 8, 16, ?",
      options: ["18", "24", "32", "30"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 3,
      question: "HTML stands for?",
      options: [
        "Hyper Text Markup Language",
        "High Transfer Machine Language",
        "Hyperlink Text Mark Language",
        "Home Tool Markup Language",
      ],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 4,
      question: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Jupiter", "Venus"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 5,
      question: "What is 9 × 7?",
      options: ["63", "56", "72", "81"],
      correctAnswerIndex: 0,
      category: "quantitative",
    },
    {
      id: 6,
      question: "CSS is used for?",
      options: [
        "Database",
        "Styling webpages",
        "Server",
        "Operating System",
      ],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 7,
      question: "Which is the largest ocean?",
      options: ["Indian", "Pacific", "Atlantic", "Arctic"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 8,
      question: "If 5x = 25, x = ?",
      options: ["3", "4", "5", "6"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 9,
      question: "React is mainly used for?",
      options: ["Backend", "Frontend", "Database", "Networking"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 10,
      question: "What is the capital of India?",
      options: ["Mumbai", "Delhi", "Chennai", "Kolkata"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 11,
      question: "Which number is odd?",
      options: ["22", "48", "37", "64"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 12,
      question: "JavaScript is a?",
      options: ["Programming Language", "Database", "Compiler", "Browser"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 13,
      question: "What is 100 ÷ 5?",
      options: ["10", "20", "25", "30"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 14,
      question: "Which gas do plants absorb?",
      options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 15,
      question: "Which symbol is used for comments in JavaScript?",
      options: ["//", "##", "<!-- -->", "**"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 16,
      question: "Find the missing number: 5, 10, 20, 40, ?",
      options: ["60", "70", "80", "90"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 17,
      question: "What is 12²?",
      options: ["124", "142", "144", "154"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 18,
      question: "MongoDB is a?",
      options: ["Database", "Language", "Framework", "Server"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 19,
      question: "Who invented the telephone?",
      options: ["Newton", "Einstein", "Alexander Graham Bell", "Tesla"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 20,
      question: "Which shape has 3 sides?",
      options: ["Square", "Triangle", "Circle", "Rectangle"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 21,
      question: "What is 81 ÷ 9?",
      options: ["7", "8", "9", "10"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 22,
      question: "Which company created Java?",
      options: ["Microsoft", "Sun Microsystems", "Google", "Apple"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 23,
      question: "Which is the fastest land animal?",
      options: ["Lion", "Tiger", "Cheetah", "Leopard"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 24,
      question: "What comes after Friday?",
      options: ["Thursday", "Saturday", "Sunday", "Monday"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 14 + 16?",
      options: ["28", "30", "32", "34"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Which HTML tag is used for links?",
      options: ["<a>", "<img>", "<h1>", "<p>"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 27,
      question: "Which country is famous for the Eiffel Tower?",
      options: ["Italy", "Germany", "France", "Spain"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 28,
      question: "Find the next number: 1, 3, 5, 7, ?",
      options: ["8", "9", "10", "11"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 50% of 200?",
      options: ["50", "75", "100", "125"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Node.js is used for?",
      options: ["Frontend", "Backend", "Design", "Animation"],
      correctAnswerIndex: 1,
      category: "technical",
    },
  ],

  // SET 2
  [
    {
      id: 31,
      question: "What is 18 + 24?",
      options: ["40", "42", "44", "46"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 32,
      question: "Which keyword declares a constant in JavaScript?",
      options: ["let", "var", "const", "static"],
      correctAnswerIndex: 2,
      category: "technical",
    },
    {
      id: 33,
      question: "Which planet has rings?",
      options: ["Mars", "Saturn", "Earth", "Mercury"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 34,
      question: "Find the next number: 10, 20, 30, 40, ?",
      options: ["45", "50", "55", "60"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 35,
      question: "What is 13 × 3?",
      options: ["39", "36", "42", "33"],
      correctAnswerIndex: 0,
      category: "quantitative",
    },
    {
      id: 36,
      question: "Which tag creates a paragraph in HTML?",
      options: ["<div>", "<p>", "<a>", "<span>"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 37,
      question: "Who is known as the Father of Computers?",
      options: ["Alan Turing", "Charles Babbage", "Newton", "Tesla"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 38,
      question: "If 8x = 64, x = ?",
      options: ["6", "7", "8", "9"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 39,
      question: "Which company developed React?",
      options: ["Google", "Meta", "Amazon", "Netflix"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 40,
      question: "What is the square root of 81?",
      options: ["7", "8", "9", "10"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 41,
      question: "Which is the smallest prime number?",
      options: ["0", "1", "2", "3"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 42,
      question: "Which language runs in the browser?",
      options: ["Python", "C++", "JavaScript", "Java"],
      correctAnswerIndex: 2,
      category: "technical",
    },
    {
      id: 43,
      question: "Which continent is India in?",
      options: ["Europe", "Asia", "Africa", "Australia"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 44,
      question: "What is 144 ÷ 12?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 45,
      question: "Which database is relational?",
      options: ["MongoDB", "MySQL", "Redis", "Firebase"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 46,
      question: "What comes next: A, C, E, G, ?",
      options: ["H", "I", "J", "K"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 47,
      question: "How many days are there in a leap year?",
      options: ["364", "365", "366", "367"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 48,
      question: "What is 25% of 80?",
      options: ["15", "20", "25", "30"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 49,
      question: "Which hook is used for state in React?",
      options: ["useRef", "useState", "useMemo", "useEffect"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 50,
      question: "Which animal is called King of the Jungle?",
      options: ["Tiger", "Elephant", "Lion", "Cheetah"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 51,
      question: "Find the missing number: 3, 6, 9, 12, ?",
      options: ["13", "14", "15", "16"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 52,
      question: "Which operator checks equality in JavaScript?",
      options: ["==", "===", "=", "!="],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 53,
      question: "What is 17 + 19?",
      options: ["34", "35", "36", "37"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 54,
      question: "Which country gifted the Statue of Liberty to the USA?",
      options: ["France", "Germany", "Italy", "Japan"],
      correctAnswerIndex: 0,
      category: "general",
    },
    {
      id: 55,
      question: "What comes after 100, 90, 80, 70?",
      options: ["50", "55", "60", "65"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 56,
      question: "Which CSS property changes text color?",
      options: ["font-size", "background", "color", "display"],
      correctAnswerIndex: 2,
      category: "technical",
    },
    {
      id: 57,
      question: "What is 11 × 11?",
      options: ["111", "121", "131", "141"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 58,
      question: "Which organ pumps blood?",
      options: ["Brain", "Heart", "Lungs", "Kidney"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 59,
      question: "Which number is divisible by 5?",
      options: ["42", "53", "65", "77"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 60,
      question: "Express.js is used with?",
      options: ["Python", "Node.js", "Java", "PHP"],
      correctAnswerIndex: 1,
      category: "technical",
    },
  ],

  // Add more sets similarly...
];
