export const aptitudeQuestionSets = [
  // SET 1
  [
    {
      id: 1,
      question: "What is 15 + 27?",
      options: ["42", "40", "45", "48"],
      correctAnswerIndex: 0,
      category: "logical",
    },
    {
      id: 2,
      question: "Which number comes next: 2, 4, 8, 16, ?",
      options: ["18", "24", "32", "30"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 3,
      question: "HTML stands for?",
      options: [
        "Hyper Text Markup Language",
        "High Transfer Machine Language",
        "Hyperlink Text Mark Language",
        "Home Tool Markup Language",
      ],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 4,
      question: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Jupiter", "Venus"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 5,
      question: "What is 9 × 7?",
      options: ["63", "56", "72", "81"],
      correctAnswerIndex: 0,
      category: "quantitative",
    },
    {
      id: 6,
      question: "CSS is used for?",
      options: ["Database", "Styling webpages", "Server", "Operating System"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 7,
      question: "Which is the largest ocean?",
      options: ["Indian", "Pacific", "Atlantic", "Arctic"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 8,
      question: "If 5x = 25, x = ?",
      options: ["3", "4", "5", "6"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 9,
      question: "React is mainly used for?",
      options: ["Backend", "Frontend", "Database", "Networking"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 10,
      question: "What is the capital of India?",
      options: ["Mumbai", "Delhi", "Chennai", "Kolkata"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 11,
      question: "Which number is odd?",
      options: ["22", "48", "37", "64"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 12,
      question: "JavaScript is a?",
      options: ["Programming Language", "Database", "Compiler", "Browser"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 13,
      question: "What is 100 ÷ 5?",
      options: ["10", "20", "25", "30"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 14,
      question: "Which gas do plants absorb?",
      options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 15,
      question: "Which symbol is used for comments in JavaScript?",
      options: ["//", "##", "<!-- -->", "**"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 16,
      question: "Find the missing number: 5, 10, 20, 40, ?",
      options: ["60", "70", "80", "90"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 17,
      question: "What is 12²?",
      options: ["124", "142", "144", "154"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 18,
      question: "MongoDB is a?",
      options: ["Database", "Language", "Framework", "Server"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 19,
      question: "Who invented the telephone?",
      options: ["Newton", "Einstein", "Alexander Graham Bell", "Tesla"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 20,
      question: "Which shape has 3 sides?",
      options: ["Square", "Triangle", "Circle", "Rectangle"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 21,
      question: "What is 81 ÷ 9?",
      options: ["7", "8", "9", "10"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 22,
      question: "Which company created Java?",
      options: ["Microsoft", "Sun Microsystems", "Google", "Apple"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 23,
      question: "Which is the fastest land animal?",
      options: ["Lion", "Tiger", "Cheetah", "Leopard"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 24,
      question: "What comes after Friday?",
      options: ["Thursday", "Saturday", "Sunday", "Monday"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 14 + 16?",
      options: ["28", "30", "32", "34"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Which HTML tag is used for links?",
      options: ["<a>", "<img>", "<h1>", "<p>"],
      correctAnswerIndex: 0,
      category: "technical",
    },
    {
      id: 27,
      question: "Which country is famous for the Eiffel Tower?",
      options: ["Italy", "Germany", "France", "Spain"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 28,
      question: "Find the next number: 1, 3, 5, 7, ?",
      options: ["8", "9", "10", "11"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 50% of 200?",
      options: ["50", "75", "100", "125"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Node.js is used for?",
      options: ["Frontend", "Backend", "Design", "Animation"],
      correctAnswerIndex: 1,
      category: "technical",
    },
  ],

  // SET 2
  [
    {
      id: 1,
      question: "What is 18 + 24?",
      options: ["40", "42", "44", "46"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 2,
      question: "Which keyword declares a constant in JavaScript?",
      options: ["let", "var", "const", "static"],
      correctAnswerIndex: 2,
      category: "technical",
    },
    {
      id: 3,
      question: "Which planet has rings?",
      options: ["Mars", "Saturn", "Earth", "Mercury"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 4,
      question: "Find the next number: 10, 20, 30, 40, ?",
      options: ["45", "50", "55", "60"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 5,
      question: "What is 13 × 3?",
      options: ["39", "36", "42", "33"],
      correctAnswerIndex: 0,
      category: "quantitative",
    },
    {
      id: 6,
      question: "Which tag creates a paragraph in HTML?",
      options: ["<div>", "<p>", "<a>", "<span>"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 7,
      question: "Who is known as the Father of Computers?",
      options: ["Alan Turing", "Charles Babbage", "Newton", "Tesla"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 8,
      question: "If 8x = 64, x = ?",
      options: ["6", "7", "8", "9"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 9,
      question: "Which company developed React?",
      options: ["Google", "Meta", "Amazon", "Netflix"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 10,
      question: "What is the square root of 81?",
      options: ["7", "8", "9", "10"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 11,
      question: "Which is the smallest prime number?",
      options: ["0", "1", "2", "3"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 12,
      question: "Which language runs in the browser?",
      options: ["Python", "C++", "JavaScript", "Java"],
      correctAnswerIndex: 2,
      category: "technical",
    },
    {
      id: 13,
      question: "Which continent is India in?",
      options: ["Europe", "Asia", "Africa", "Australia"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 14,
      question: "What is 144 ÷ 12?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 15,
      question: "Which database is relational?",
      options: ["MongoDB", "MySQL", "Redis", "Firebase"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 16,
      question: "What comes next: A, C, E, G, ?",
      options: ["H", "I", "J", "K"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 17,
      question: "How many days are there in a leap year?",
      options: ["364", "365", "366", "367"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 18,
      question: "What is 25% of 80?",
      options: ["15", "20", "25", "30"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 19,
      question: "Which hook is used for state in React?",
      options: ["useRef", "useState", "useMemo", "useEffect"],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 20,
      question: "Which animal is called King of the Jungle?",
      options: ["Tiger", "Elephant", "Lion", "Cheetah"],
      correctAnswerIndex: 2,
      category: "general",
    },
    {
      id: 21,
      question: "Find the missing number: 3, 6, 9, 12, ?",
      options: ["13", "14", "15", "16"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 22,
      question: "Which operator checks equality in JavaScript?",
      options: ["==", "===", "=", "!="],
      correctAnswerIndex: 1,
      category: "technical",
    },
    {
      id: 23,
      question: "What is 17 + 19?",
      options: ["34", "35", "36", "37"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 24,
      question: "Which country gifted the Statue of Liberty to the USA?",
      options: ["France", "Germany", "Italy", "Japan"],
      correctAnswerIndex: 0,
      category: "general",
    },
    {
      id: 25,
      question: "What comes after 100, 90, 80, 70?",
      options: ["50", "55", "60", "65"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 26,
      question: "Which CSS property changes text color?",
      options: ["font-size", "background", "color", "display"],
      correctAnswerIndex: 2,
      category: "technical",
    },
    {
      id: 27,
      question: "What is 11 × 11?",
      options: ["111", "121", "131", "141"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 28,
      question: "Which organ pumps blood?",
      options: ["Brain", "Heart", "Lungs", "Kidney"],
      correctAnswerIndex: 1,
      category: "general",
    },
    {
      id: 29,
      question: "Which number is divisible by 5?",
      options: ["42", "53", "65", "77"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 30,
      question: "Express.js is used with?",
      options: ["Python", "Node.js", "Java", "PHP"],
      correctAnswerIndex: 1,
      category: "technical",
    },
  ],

  //Set 3
  [
    {
      id: 1,
      question: "What is 18 + 24?",
      options: ["42", "40", "44", "46"],
      correctAnswerIndex: 0,
      category: "logical",
    },
    {
      id: 2,
      question:
        "If a train travels 60 km in 1 hour, how far will it travel in 3 hours?",
      options: ["120 km", "180 km", "150 km", "200 km"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 3,
      question: "Which number comes next in the series: 2, 4, 8, 16, ?",
      options: ["18", "20", "24", "32"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 4,
      question: "What is 25% of 200?",
      options: ["25", "40", "50", "60"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 5,
      question: "If ALL = 12, BALL = ?",
      options: ["24", "30", "32", "36"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 6,
      question:
        "A clock shows 3:15. What is the angle between the hour and minute hands?",
      options: ["0°", "7.5°", "15°", "22.5°"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 7,
      question: "What is the square root of 144?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 8,
      question: "Find the odd one out: Apple, Banana, Carrot, Mango",
      options: ["Apple", "Banana", "Carrot", "Mango"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 9,
      question:
        "If 5 workers complete a task in 10 days, how many days will 10 workers take?",
      options: ["2", "4", "5", "8"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 10,
      question: "Which word is opposite of 'Expand'?",
      options: ["Grow", "Increase", "Shrink", "Spread"],
      correctAnswerIndex: 2,
      category: "verbal",
    },
    {
      id: 11,
      question: "What is 9 × 8?",
      options: ["72", "64", "81", "78"],
      correctAnswerIndex: 0,
      category: "quantitative",
    },
    {
      id: 12,
      question: "If CAT = 24, DOG = ?",
      options: ["26", "30", "32", "35"],
      correctAnswerIndex: 0,
      category: "logical",
    },
    {
      id: 13,
      question: "Find the next number: 5, 10, 20, 40, ?",
      options: ["60", "70", "80", "90"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 14,
      question: "What is 30% of 500?",
      options: ["100", "120", "150", "180"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 15,
      question: "Choose the synonym of 'Rapid'",
      options: ["Slow", "Fast", "Weak", "Short"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 16,
      question:
        "A shopkeeper buys an item for ₹200 and sells it for ₹250. What is the profit?",
      options: ["₹40", "₹45", "₹50", "₹60"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 17,
      question: "Which number is divisible by both 2 and 5?",
      options: ["15", "18", "20", "23"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 18,
      question: "What is the average of 10, 20, and 30?",
      options: ["15", "20", "25", "30"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 19,
      question: "Find the missing letter: A, C, E, G, ?",
      options: ["H", "I", "J", "K"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 20,
      question: "Choose the correct spelling.",
      options: ["Definately", "Definetely", "Definitely", "Defnatly"],
      correctAnswerIndex: 2,
      category: "verbal",
    },
    {
      id: 21,
      question: "What is 7²?",
      options: ["42", "47", "49", "56"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 22,
      question:
        "If a car moves at 50 km/h, how much distance will it cover in 2 hours?",
      options: ["80 km", "90 km", "100 km", "120 km"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 23,
      question: "Which shape has 3 sides?",
      options: ["Square", "Rectangle", "Triangle", "Circle"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 24,
      question: "Find the next number: 1, 4, 9, 16, ?",
      options: ["20", "25", "30", "36"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 100 ÷ 4?",
      options: ["20", "25", "30", "35"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Choose the antonym of 'Brave'",
      options: ["Bold", "Fearful", "Strong", "Confident"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 27,
      question: "If 12 pencils cost ₹60, what is the cost of 1 pencil?",
      options: ["₹2", "₹3", "₹4", "₹5"],
      correctAnswerIndex: 3,
      category: "quantitative",
    },
    {
      id: 28,
      question: "Find the odd number: 2, 4, 6, 9, 10",
      options: ["2", "4", "6", "9"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 45 + 55?",
      options: ["90", "95", "100", "110"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Choose the correct sentence.",
      options: [
        "She do her work.",
        "She does her work.",
        "She doing her work.",
        "She done her work.",
      ],
      correctAnswerIndex: 1,
      category: "verbal",
    },
  ],

  //Set 4
  [
    {
      id: 1,
      question: "What is 32 + 18?",
      options: ["45", "48", "50", "52"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 2,
      question: "Find the next number: 3, 6, 12, 24, ?",
      options: ["36", "42", "48", "54"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 3,
      question: "What is 15% of 400?",
      options: ["40", "50", "60", "70"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 4,
      question: "Choose the synonym of 'Happy'.",
      options: ["Sad", "Joyful", "Angry", "Weak"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 5,
      question: "If a bus travels 240 km in 4 hours, what is its speed?",
      options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 6,
      question: "Which number is the odd one out: 11, 13, 17, 20, 23?",
      options: ["11", "13", "17", "20"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 7,
      question: "What is the square root of 225?",
      options: ["12", "13", "14", "15"],
      correctAnswerIndex: 3,
      category: "quantitative",
    },
    {
      id: 8,
      question: "Choose the antonym of 'Strong'.",
      options: ["Powerful", "Weak", "Bold", "Hard"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 9,
      question: "Find the missing number: 2, 5, 8, 11, ?",
      options: ["13", "14", "15", "16"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 10,
      question: "What is 84 ÷ 7?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 11,
      question: "If PEN = 35, then BOOK = ?",
      options: ["41", "43", "45", "47"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 12,
      question:
        "A product costs ₹500. A 10% discount is given. What is the final price?",
      options: ["₹400", "₹450", "₹470", "₹480"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 13,
      question: "Choose the correct spelling.",
      options: ["Enviroment", "Environment", "Envirnment", "Enviornment"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 14,
      question: "Find the next letter: B, D, F, H, ?",
      options: ["I", "J", "K", "L"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 15,
      question: "What is 9 + 19?",
      options: ["26", "27", "28", "29"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 16,
      question: "A man earns ₹800 per day. How much will he earn in 5 days?",
      options: ["₹3500", "₹4000", "₹4500", "₹5000"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 17,
      question: "Find the odd one out: Rose, Lotus, Lily, Carrot",
      options: ["Rose", "Lotus", "Lily", "Carrot"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 18,
      question: "What is 40% of 250?",
      options: ["80", "90", "100", "110"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 19,
      question: "Choose the synonym of 'Smart'.",
      options: ["Dull", "Lazy", "Intelligent", "Weak"],
      correctAnswerIndex: 2,
      category: "verbal",
    },
    {
      id: 20,
      question: "Find the next number: 10, 20, 30, 40, ?",
      options: ["45", "50", "55", "60"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 21,
      question: "What is 11 × 11?",
      options: ["111", "121", "131", "141"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 22,
      question: "A train covers 90 km in 2 hours. What is its speed?",
      options: ["40 km/h", "45 km/h", "50 km/h", "55 km/h"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 23,
      question: "Choose the correct sentence.",
      options: [
        "They is playing football.",
        "They are playing football.",
        "They was playing football.",
        "They plays football.",
      ],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 24,
      question: "Find the missing number: 1, 3, 6, 10, ?",
      options: ["12", "14", "15", "16"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 144 ÷ 12?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Choose the antonym of 'Early'.",
      options: ["Late", "Fast", "Quick", "Soon"],
      correctAnswerIndex: 0,
      category: "verbal",
    },
    {
      id: 27,
      question: "If 8 notebooks cost ₹240, what is the cost of 1 notebook?",
      options: ["₹20", "₹25", "₹30", "₹35"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 28,
      question: "Find the odd number: 4, 8, 12, 15, 20",
      options: ["4", "8", "12", "15"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 75 - 28?",
      options: ["45", "47", "49", "52"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Choose the correct spelling.",
      options: ["Recieve", "Receive", "Receeve", "Receve"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
  ],

  // Set 5
  [
    {
      id: 1,
      question: "What is 48 + 27?",
      options: ["65", "70", "75", "80"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 2,
      question: "Find the next number: 5, 10, 15, 20, ?",
      options: ["22", "24", "25", "30"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 3,
      question: "What is 20% of 350?",
      options: ["60", "65", "70", "75"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 4,
      question: "Choose the synonym of 'Begin'.",
      options: ["Start", "Stop", "End", "Pause"],
      correctAnswerIndex: 0,
      category: "verbal",
    },
    {
      id: 5,
      question: "If a bike travels 150 km in 3 hours, what is its speed?",
      options: ["40 km/h", "45 km/h", "50 km/h", "55 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 6,
      question: "Which number is the odd one out: 2, 4, 6, 7, 8?",
      options: ["2", "4", "6", "7"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 7,
      question: "What is the square root of 169?",
      options: ["11", "12", "13", "14"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 8,
      question: "Choose the antonym of 'Hot'.",
      options: ["Warm", "Cold", "Heat", "Boil"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 9,
      question: "Find the missing number: 4, 8, 12, 16, ?",
      options: ["18", "20", "22", "24"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 10,
      question: "What is 96 ÷ 8?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 11,
      question: "If CAR = 24, then BUS = ?",
      options: ["40", "42", "43", "44"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 12,
      question:
        "A shirt costs ₹800. After a 25% discount, what is the final price?",
      options: ["₹500", "₹550", "₹600", "₹650"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 13,
      question: "Choose the correct spelling.",
      options: ["Occasion", "Ocassion", "Occassion", "Occsion"],
      correctAnswerIndex: 0,
      category: "verbal",
    },
    {
      id: 14,
      question: "Find the next letter: C, F, I, L, ?",
      options: ["M", "N", "O", "P"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 15,
      question: "What is 14 + 29?",
      options: ["41", "42", "43", "44"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 16,
      question: "A worker earns ₹600 per day. How much will he earn in 7 days?",
      options: ["₹3600", "₹4000", "₹4200", "₹4500"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 17,
      question: "Find the odd one out: Mango, Apple, Banana, Potato",
      options: ["Mango", "Apple", "Banana", "Potato"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 18,
      question: "What is 50% of 180?",
      options: ["80", "85", "90", "95"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 19,
      question: "Choose the synonym of 'Large'.",
      options: ["Tiny", "Huge", "Short", "Weak"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 20,
      question: "Find the next number: 7, 14, 21, 28, ?",
      options: ["30", "32", "35", "36"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 21,
      question: "What is 13 × 9?",
      options: ["107", "117", "127", "137"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 22,
      question: "A car covers 120 km in 2 hours. What is its speed?",
      options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 23,
      question: "Choose the correct sentence.",
      options: [
        "He go to school daily.",
        "He goes to school daily.",
        "He going to school daily.",
        "He gone to school daily.",
      ],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 24,
      question: "Find the missing number: 2, 6, 12, 20, ?",
      options: ["28", "30", "32", "36"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 121 ÷ 11?",
      options: ["9", "10", "11", "12"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Choose the antonym of 'Rich'.",
      options: ["Wealthy", "Poor", "Strong", "Healthy"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 27,
      question: "If 5 pens cost ₹75, what is the cost of 1 pen?",
      options: ["₹10", "₹12", "₹15", "₹18"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 28,
      question: "Find the odd number: 9, 18, 27, 35, 45",
      options: ["9", "18", "27", "35"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 88 - 39?",
      options: ["47", "48", "49", "50"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Choose the correct spelling.",
      options: ["Succesful", "Successful", "Succesfull", "Succesfull"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
  ],

  // Set 6

  [
    {
      id: 1,
      question: "What is 56 + 19?",
      options: ["73", "74", "75", "76"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 2,
      question: "Find the next number: 6, 12, 18, 24, ?",
      options: ["28", "30", "32", "36"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 3,
      question: "What is 35% of 200?",
      options: ["60", "65", "70", "75"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 4,
      question: "Choose the synonym of 'Quick'.",
      options: ["Slow", "Fast", "Weak", "Calm"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 5,
      question: "If a train travels 300 km in 5 hours, what is its speed?",
      options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 6,
      question: "Find the odd one out: 14, 16, 18, 21, 22",
      options: ["14", "16", "18", "21"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 7,
      question: "What is the square root of 196?",
      options: ["12", "13", "14", "15"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 8,
      question: "Choose the antonym of 'Bright'.",
      options: ["Shiny", "Smart", "Dark", "Light"],
      correctAnswerIndex: 2,
      category: "verbal",
    },
    {
      id: 9,
      question: "Find the missing number: 3, 9, 15, 21, ?",
      options: ["24", "25", "27", "30"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 10,
      question: "What is 108 ÷ 9?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 11,
      question: "If DOG = 26, then CAT = ?",
      options: ["22", "24", "26", "28"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 12,
      question:
        "A watch costs ₹1200. After a 20% discount, what is the final price?",
      options: ["₹900", "₹960", "₹1000", "₹1100"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 13,
      question: "Choose the correct spelling.",
      options: ["Beautifull", "Beautiful", "Beutiful", "Beautifal"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 14,
      question: "Find the next letter: D, G, J, M, ?",
      options: ["N", "O", "P", "Q"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 15,
      question: "What is 27 + 38?",
      options: ["63", "64", "65", "66"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 16,
      question: "A person earns ₹900 daily. How much will he earn in 6 days?",
      options: ["₹5000", "₹5200", "₹5400", "₹5600"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 17,
      question: "Find the odd one out: Tiger, Lion, Elephant, Rose",
      options: ["Tiger", "Lion", "Elephant", "Rose"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 18,
      question: "What is 60% of 150?",
      options: ["70", "80", "90", "100"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 19,
      question: "Choose the synonym of 'Tiny'.",
      options: ["Huge", "Small", "Tall", "Wide"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 20,
      question: "Find the next number: 8, 16, 24, 32, ?",
      options: ["36", "38", "40", "42"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 21,
      question: "What is 14 × 8?",
      options: ["102", "112", "122", "132"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 22,
      question: "A bike covers 180 km in 3 hours. What is its speed?",
      options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 23,
      question: "Choose the correct sentence.",
      options: [
        "She have completed the task.",
        "She has completed the task.",
        "She completed has the task.",
        "She having completed the task.",
      ],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 24,
      question: "Find the missing number: 5, 10, 20, 40, ?",
      options: ["60", "70", "80", "90"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 169 ÷ 13?",
      options: ["11", "12", "13", "14"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Choose the antonym of 'Clean'.",
      options: ["Dirty", "Fresh", "Clear", "Pure"],
      correctAnswerIndex: 0,
      category: "verbal",
    },
    {
      id: 27,
      question: "If 4 bags cost ₹200, what is the cost of 1 bag?",
      options: ["₹40", "₹45", "₹50", "₹55"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 28,
      question: "Find the odd number: 12, 24, 36, 49, 60",
      options: ["12", "24", "36", "49"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 95 - 47?",
      options: ["46", "47", "48", "49"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Choose the correct spelling.",
      options: ["Knowlege", "Knowledge", "Knowladge", "Knowlegee"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
  ],

  // Set 7

  [
    {
      id: 1,
      question: "What is 64 + 18?",
      options: ["80", "81", "82", "84"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 2,
      question: "Find the next number: 7, 14, 21, 28, ?",
      options: ["32", "35", "38", "42"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 3,
      question: "What is 45% of 200?",
      options: ["70", "80", "90", "100"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 4,
      question: "Choose the synonym of 'Strong'.",
      options: ["Weak", "Powerful", "Soft", "Light"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 5,
      question: "If a car travels 240 km in 4 hours, what is its speed?",
      options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 6,
      question: "Find the odd one out: 5, 10, 15, 18, 20",
      options: ["5", "10", "15", "18"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 7,
      question: "What is the square root of 256?",
      options: ["14", "15", "16", "17"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 8,
      question: "Choose the antonym of 'Old'.",
      options: ["Ancient", "Young", "Weak", "Tall"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 9,
      question: "Find the missing number: 2, 4, 8, 16, ?",
      options: ["24", "28", "32", "36"],
      correctAnswerIndex: 2,
      category: "logical",
    },
    {
      id: 10,
      question: "What is 144 ÷ 12?",
      options: ["10", "11", "12", "13"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 11,
      question: "If BAT = 23, then BALL = ?",
      options: ["30", "32", "34", "36"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 12,
      question:
        "A phone costs ₹15000. After a 10% discount, what is the final price?",
      options: ["₹13000", "₹13500", "₹14000", "₹14500"],
      correctAnswerIndex: 1,
      category: "quantitative",
    },
    {
      id: 13,
      question: "Choose the correct spelling.",
      options: ["Succes", "Success", "Sucess", "Sucsess"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 14,
      question: "Find the next letter: E, H, K, N, ?",
      options: ["P", "Q", "R", "S"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 15,
      question: "What is 46 + 29?",
      options: ["73", "74", "75", "76"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 16,
      question: "A laborer earns ₹700 daily. How much will he earn in 8 days?",
      options: ["₹5200", "₹5400", "₹5600", "₹5800"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 17,
      question: "Find the odd one out: Cow, Goat, Sheep, Chair",
      options: ["Cow", "Goat", "Sheep", "Chair"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 18,
      question: "What is 75% of 120?",
      options: ["80", "85", "90", "95"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 19,
      question: "Choose the synonym of 'Easy'.",
      options: ["Simple", "Hard", "Complex", "Heavy"],
      correctAnswerIndex: 0,
      category: "verbal",
    },
    {
      id: 20,
      question: "Find the next number: 9, 18, 27, 36, ?",
      options: ["42", "45", "48", "50"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 21,
      question: "What is 15 × 7?",
      options: ["95", "100", "105", "110"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 22,
      question: "A train covers 210 km in 3 hours. What is its speed?",
      options: ["60 km/h", "65 km/h", "70 km/h", "75 km/h"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 23,
      question: "Choose the correct sentence.",
      options: [
        "They has finished the work.",
        "They have finished the work.",
        "They finishing the work.",
        "They finished has the work.",
      ],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 24,
      question: "Find the missing number: 1, 4, 9, 16, ?",
      options: ["20", "25", "30", "36"],
      correctAnswerIndex: 1,
      category: "logical",
    },
    {
      id: 25,
      question: "What is 225 ÷ 15?",
      options: ["13", "14", "15", "16"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 26,
      question: "Choose the antonym of 'Happy'.",
      options: ["Joyful", "Sad", "Excited", "Glad"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
    {
      id: 27,
      question: "If 6 bottles cost ₹180, what is the cost of 1 bottle?",
      options: ["₹20", "₹25", "₹30", "₹35"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 28,
      question: "Find the odd number: 8, 16, 24, 31, 40",
      options: ["8", "16", "24", "31"],
      correctAnswerIndex: 3,
      category: "logical",
    },
    {
      id: 29,
      question: "What is 120 - 68?",
      options: ["50", "51", "52", "53"],
      correctAnswerIndex: 2,
      category: "quantitative",
    },
    {
      id: 30,
      question: "Choose the correct spelling.",
      options: ["Acommodation", "Accommodation", "Accomodation", "Acomodation"],
      correctAnswerIndex: 1,
      category: "verbal",
    },
  ],
  // Add more sets similarly...
];
